import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/ui/SmoothScroll";
import { AOSInit } from "./components/AOSInit";
import Header from "./components/layout/Header";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  display: "swap",
  // axes: [""], // Enable optical sizing for display-quality rendering
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${figtree.className} leading-tight! tracking-tight! antialiased bg-white!`}>
        <SmoothScroll>
          <Header />
          <AOSInit />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
